serve:
  port: 80
  browser: false
  playground: true
  endpoint: /mesh
  playgroundTitle: Gebouw Dossier Demo Playground

sources:
  - name: CBS85496NED
    handler:
      odata:
        endpoint: https://opendata.cbs.nl/ODataApi/odata/85496NED/
        source: ./CBS85496.xml
        expandNavProps: true
    transforms:
      - prefix:
          value: CBS85496
          includeRootOperations: true
  - name: CBS70072ned 
    handler:
      odata:
        endpoint: https://opendata.cbs.nl/ODataApi/odata/70072ned/
        source: ./CBS70072.xml
        expandNavProps: true
    transform:
      - prefix:
          value: CBS70072
          includeRootOperations: true
        
  - name: LOC
    handler:
      openapi:
        source: ./locatieserver_openapi.yaml
        endpoint: https://api.pdok.nl/bzk/locatieserver/search/v3_1/
        ignoreErrorResponses: true
    transforms:
      - prefix:
          value: LOC
          includeRootOperations: true
