serve:
  port: 80
  browser: false
  playground: true
  endpoint: /mesh
  playgroundTitle: CBS Demo Playground

sources:
  - name: CBS
    handler:
      openapi:
        source: ./cbsopenapi.json
        endpoint: https://www.cbs.nl/odata/v1/
        ignoreErrorResponses: true
        operationHeaders:
          Content-Type: application/json
    transforms:
      - prefix:
          value: CBS
          includeRootOperations: true

  - name: CBS85496NED
    handler:
      odata:
        endpoint: https://opendata.cbs.nl/ODataApi/odata/85496NED/
        source: ./CBS85496.xml
        expandNavProps: true
    transforms:
      - prefix:
          value: CBS85496
          includeRootOperations: true
          
  - name: CBS70072ned
    handler:
      odata:
        endpoint: https://opendata.cbs.nl/ODataApi/odata/70072ned/
        source: ./CBS70072.xml
        expandNavProps: true
    transforms:
      - prefix:
          value: CBS70072
          includeRootOperations: true
          
  - name: CBS85814NED
    handler: 
      odata:
        endpoint: https://opendata.cbs.nl/ODataApi/odata/85814NED/
        source: ./CBS85814.xml
        expandNavProps: true
    transforms: 
      - prefix:
          value: CBS85814
          includeRootOperations: true
          
  - name: LOC
    handler:
      openapi:
        source: ./locatieserver_openapi.yaml
        endpoint: https://api.pdok.nl/bzk/locatieserver/search/v3_1/
        ignoreErrorResponses: true
    transforms:
      - prefix:
          value: LOC
          includeRootOperations: true
